name: CI/CD - Build & Deploy to Linux

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Fix AJV version (avoid build errors)
      - name: Fix AJV version
        run: npm install ajv@6.12.6 ajv-keywords@3.5.2 --save-dev --legacy-peer-deps

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 5️⃣ Build React app
      - name: Build React App
        run: npm run build

      # 6️⃣ Setup SSH agent
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 7️⃣ Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" \
          "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "echo ✅ SSH key auth working"
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      # 8️⃣ Deploy build folder to EC2
      - name: Deploy to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
          build/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}/"

      # 9️⃣ Restart Nginx
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" \
          "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "sudo systemctl restart nginx"
